### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by RoseSecurity** [Kleptocratic/WindowsKiller#2]
![WindowsKiller](https://user-images.githubusercontent.com/72598486/130345543-f3219aaa-651f-4787-8bd5-7614f6e0f731.png)

**Comment by TomerGamerTV** [comment]
[update the image
](https://www.virustotal.com/gui/file/6cf96e94b8ebcf96d1669835a553818753aa143a7430b165252a49d60ae8fdf5)
